{
  "error": {
    "root_cause": [
      {
        "type": "snapshot_restore_exception",
        "reason": "[biopharma-cosine-repository:biopharmacosine/HO85El7TRoilNrMCpApN2g] cannot restore index [test-mapping-updated] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"
      }
    ],
    "type": "snapshot_restore_exception",
    "reason": "[biopharma-cosine-repository:biopharmacosine/HO85El7TRoilNrMCpApN2g] cannot restore index [test-mapping-updated] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"
  },
  "status": 500
}
